// Mock data for the jewelry website

export const products = [
  {
    id: 1,
    name: "Eternal Diamond Ring",
    slug: "eternal-diamond-ring",
    price: 2499,
    category: "rings",
    material: "Gold",
    description:
      "A timeless 18k gold ring featuring a brilliant-cut diamond that captures the essence of eternal love.",
    image: "/luxury-diamond-ring.jpg",
    collection: "signature",
  },
  {
    id: 2,
    name: "Celestial Pearl Necklace",
    slug: "celestial-pearl-necklace",
    price: 3299,
    category: "necklaces",
    material: "Gold",
    description: "Handcrafted 18k gold necklace adorned with rare South Sea pearls, exemplifying refined elegance.",
    image: "/luxury-pearl-necklace.jpg",
    collection: "signature",
  },
  {
    id: 3,
    name: "Radiance Sapphire Earrings",
    slug: "radiance-sapphire-earrings",
    price: 1899,
    category: "earrings",
    material: "White Gold",
    description: "Exquisite white gold earrings featuring deep blue sapphires surrounded by delicate diamond accents.",
    image: "/luxury-sapphire-earrings.jpg",
    collection: "royal",
  },
  {
    id: 4,
    name: "Heritage Gold Bracelet",
    slug: "heritage-gold-bracelet",
    price: 1599,
    category: "bracelets",
    material: "Gold",
    description: "A stunning 22k gold bracelet inspired by classical designs, perfect for any occasion.",
    image: "/luxury-gold-bracelet.jpg",
    collection: "heritage",
  },
  {
    id: 5,
    name: "Infinity Emerald Ring",
    slug: "infinity-emerald-ring",
    price: 2899,
    category: "rings",
    material: "Platinum",
    description: "Platinum ring showcasing a vibrant emerald stone symbolizing infinite beauty and grace.",
    image: "/luxury-emerald-ring.jpg",
    collection: "signature",
  },
  {
    id: 6,
    name: "Lumière Diamond Pendant",
    slug: "lumiere-diamond-pendant",
    price: 2199,
    category: "necklaces",
    material: "White Gold",
    description: "Elegant white gold pendant featuring a solitaire diamond that radiates timeless brilliance.",
    image: "/luxury-diamond-pendant.jpg",
    collection: "signature",
  },
  {
    id: 7,
    name: "Royal Ruby Brooch",
    slug: "royal-ruby-brooch",
    price: 3599,
    category: "brooches",
    material: "Gold",
    description: "Magnificent 18k gold brooch adorned with Burmese rubies, a statement of regal sophistication.",
    image: "/luxury-ruby-brooch.jpg",
    collection: "royal",
  },
  {
    id: 8,
    name: "Serenity Moonstone Ring",
    slug: "serenity-moonstone-ring",
    price: 1399,
    category: "rings",
    material: "Silver",
    description: "Sterling silver ring featuring a captivating moonstone that embodies tranquil beauty.",
    image: "/luxury-moonstone-ring.jpg",
    collection: "heritage",
  },
]

export const collections = [
  {
    id: 1,
    name: "Signature Collection",
    slug: "signature",
    description: "Our most iconic pieces, crafted to perfection with timeless elegance and exceptional quality.",
    image: "/luxury-jewelry-signature-collection.jpg",
    productCount: 4,
  },
  {
    id: 2,
    name: "Royal Collection",
    slug: "royal",
    description:
      "Regal pieces inspired by centuries of aristocratic heritage, featuring rare gemstones and intricate craftsmanship.",
    image: "/luxury-jewelry-royal-collection.jpg",
    productCount: 2,
  },
  {
    id: 3,
    name: "Heritage Collection",
    slug: "heritage",
    description: "Classic designs that honor traditional jewelry-making techniques passed down through generations.",
    image: "/luxury-jewelry-heritage-collection.jpg",
    productCount: 2,
  },
]

export const blogs = [
  {
    id: 1,
    title: "The Art of Diamond Selection",
    slug: "art-of-diamond-selection",
    excerpt: "Discover the four Cs of diamond quality and learn how to choose the perfect stone for your jewelry.",
    content: "When selecting a diamond, understanding the four Cs—Cut, Color, Clarity, and Carat—is essential...",
    image: "/diamond-selection-guide.jpg",
    date: "2024-01-15",
    author: "Sarah Mitchell",
  },
  {
    id: 2,
    title: "Caring for Your Fine Jewelry",
    slug: "caring-for-fine-jewelry",
    excerpt: "Essential tips and techniques to maintain the brilliance and beauty of your precious jewelry pieces.",
    content: "Fine jewelry requires special care to preserve its luster and integrity over the years...",
    image: "/jewelry-care-maintenance.jpg",
    date: "2024-01-20",
    author: "James Anderson",
  },
  {
    id: 3,
    title: "Trends in Luxury Jewelry 2024",
    slug: "luxury-jewelry-trends-2024",
    excerpt: "Explore the latest trends shaping the world of high-end jewelry design this year.",
    content: "This year, we see a resurgence of vintage-inspired designs combined with modern minimalism...",
    image: "/luxury-jewelry-trends-2024.jpg",
    date: "2024-02-01",
    author: "Emma Thompson",
  },
  {
    id: 4,
    title: "The History of Pearl Jewelry",
    slug: "history-of-pearl-jewelry",
    excerpt: "Journey through centuries of pearl cultivation and its significance in fine jewelry.",
    content: "Pearls have captivated humanity for millennia, from ancient Roman empresses to modern fashion icons...",
    image: "/pearl-jewelry-history.jpg",
    date: "2024-02-10",
    author: "Sarah Mitchell",
  },
]
